# MAIN CONSTANTS
ZORB_INITIAL_LIFENESS = 100.0


# REDIS KEYS
REDIS_ZORBS = "zorbs"
REDIS_ZORB_PREFIX = "zorb/"
REDIS_ZORBS_PROCESSING = "zorbs/processing"
REDIS_ZORBS_PROCESSED = "zorbs/processed"
REDIS_WORLD = "world"

# ENVIRONMENT KEYS
ENV_REDIS_CONF = "LIFE_REDIS_CONF"


# DAY_REDUCTION
DAY_REDUCE_ENERGY = 100
DAY_REDUCE_LIFENESS = .5

# ENERGY
ENERGY_QUANTUM = 10


# EVENT
REDIS_EVENTS = "events"
REDIS_EVENTS_TYPE = "events/{type}"
REDIS_EVENTS_PREFIX = "event/{type}/{id}"
